name:                buzgibi
version:             0.0.1
license:             BSD-3-Clause
author:              "Buzgibi"
maintainer:
 - "Sergey Yakovlev, home<fclaw007@gmail.com>"
copyright:           "2023"
ghc-options:
  - -threaded
  - -rtsopts
  - -O2
  - -Werror
  - -fwarn-unused-imports
  - -Wredundant-constraints
  - -Wduplicate-exports
  - -Widentities
  - -Wincomplete-record-updates
  - -Wmissing-fields
  - -Wmissing-exported-signatures
  - -Wunused-binds
  - -Wwrong-do-bind
  - -Wcpp-undef
  - -Wunused-do-bind
  - -Wunused-pattern-binds
  - -Wtabs
  - -Wmissing-pattern-synonym-signatures
  - -fwrite-ide-info
  - -hiedir=.hie
  - -optP-Wno-nonportable-include-path

# verbatim:
#   cabal-version: 2.4

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/buzgibi-ai/back/blob/master/README.md>

dependencies:
    - base >= 4.7 && < 5
# - relude ^>= 0.6.0.0
# - name: base
#   mixin:
#    - hiding (Prelude)
# - name: relude
#   mixin:
#    - (Relude as Prelude
#      , Relude.Extra.Enum
#      , Relude.Extra.Validation
#      , Relude.Unsafe
#      )

library:
  dependencies:
    - tasty
    - tasty-hspec
    - tasty-hunit
    - tasty-html
    - aeson
    - lens
    - lens-aeson
    - async
    - lifted-async
    - monad-control
    - text
    - bytestring
    - containers
    - template-haskell
    - yaml
    - extra
    - colorful-monoids
    - hspec
    - resource-pool
    - tmp-postgres
    - directory
    - filepath
    - time
    - pretty-simple == 3.2.1.0
    - brick
    - process
    - random
    - servant
    - servant-server
    - katip
    - transformers-base
    - mtl
    - transformers
    - servant-server
    - warp
    - rotating-log
    - doctest
    - doctest-discover
    - tasty-discover
    - hasql
    - hasql-th
    - exceptions
    - validation-selective
    - pretty-tree
    - rosezipper
    - servant-swagger-ui
    - servant-swagger-ui-core
    - servant-swagger
    - swagger2
    - wai-app-static
    - jose
    - either
    - generic-lens
    - scientific
    - vector
    - deepseq
    - QuickCheck
    - safe-exceptions
    - wai
    - casing
    - lifted-base
    - data-default-class
    - postgresql-error-codes
    - string-interpolate 
    - http-client
    - http-client-tls
    - memory
    - http-types
    - unordered-containers
    - utf8-string
    - wai-cors
    - monad-time
    - tagged
    - resourcet
    - monad-loops
    - sort
    - contravariant-extras
    - lens-aeson
    - hashing
    - strict
    - optparse-generic
    - hspec-expectations-lifted
    - minio-hs
    - network-ip
    - data-textual
    - servant-client-core
    - binary
    - hashable
    - text-show
    - foldl
    - servant-multipart
    - servant-rawm
    - servant-rawm-server
    - wai-extra
    - conduit
    - errors
    - string-conversions
    - data-default
    - elocrypt
    - tuple-sop
    - generic-random
    - generic-deriving
    - ghc-prim
    - base64-bytestring
    - generic-arbitrary
    - insert-ordered-containers
    - generics-sop
    - string-conv
    - warp-tls
    - crypto-random
    - network
    - mime-types
    - cprng-aes
    - ginger
    - reflection
    - cryptonite
    - servant-auth-server
    - servant-auth-swagger
    - stm
    - threads
    - http-api-data
    - servant-websockets
    - websockets
    - aeson-pretty
    - lifted-async
    - http-conduit
    - sendgrid
    - github
    - quickcheck-instances
    - unliftio-core
    - unliftio
    - katip-wai
    - cassava
    - xlsx
    - conduit-extra
    - regex-with-pcre
    - stm-chans
    - retry
    - hasql-notifications
    - stm-lifted
    - uuid
    - google-oauth2-jwt

  source-dirs:
    - src/core
    - src/extended

executables:
  buzgibi:
    main:                Main.hs
    source-dirs:         
      - src/main
    dependencies:
      - buzgibi
      - directory
      - text
      - lens
      - katip
      - resource-pool
      - hasql
      - containers
      - time
      - minio-hs
      - optparse-generic
      - http-client
      - colorful-monoids
      - data-default-class
      - mtl
      - http-client-tls
      - filepath
      - jose
      - bytestring
      - either
      - aeson
      - string-conv

tests:
  tasty:
    main:                test.hs
    source-dirs:
       - prog
       - test
    dependencies:
    - buzgibi
    - servant
    - hspec
    - servant-swagger
    - generic-lens
    - lens
    - hspec-expectations-lifted
    - QuickCheck
    - hasql
    - tasty
    - tasty-hspec
    - tasty-html
